/************************ Employees table inserts ************************/
SET IDENTITY_INSERT [dbo].[Employees] ON

INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (1, NULL, 'Huntington', 'Craig', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (2, NULL, 'Sauro', 'Denise', 'West/Central (UT)')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (6, NULL, 'Ostwinkle', 'Amy', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (9, NULL, 'Haluska', 'Joanne', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (11, NULL, 'Huntington', 'Craig Lee', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (17, NULL, 'Dyer', 'Stacy', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (19, NULL, 'Nordstrom', 'Judy', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (20, NULL, 'Wagner', 'JoAnn', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (23, NULL, 'Holton', 'Sabine', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (27, NULL, 'Knuth', 'Paul', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (28, NULL, 'Small', 'Robert', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (29, NULL, 'Burkhammer', 'Tracy', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (38, NULL, 'Kerick', 'James', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (44, NULL, 'Elkan', 'Lisa', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (46, NULL, 'McKee', 'Andrea', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (49, NULL, 'Harshey', 'Sarah', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (52, NULL, 'Hillen', 'Pat', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (53, NULL, 'Stevens', 'Dennis', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (54, NULL, 'Kane', 'Stephanie', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (56, NULL, 'Caples', 'Kristy', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (57, NULL, 'Langebrake', 'Teresa', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (58, NULL, 'Eldean', 'John', 'Unknown')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (62, NULL, 'Raley', 'Brittney', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (66, NULL, 'Valles', 'Rosy', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (67, NULL, 'Hardy', 'Bert', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (69, NULL, 'Cardoza', 'Linda', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (70, NULL, 'Fox', 'Blair', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (71, NULL, 'Lanemann', 'Bradley', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (72, NULL, 'Villanueva', 'Carolina', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (73, NULL, 'Young', 'Venyse', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (74, NULL, 'Videen', 'John', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (75, NULL, 'Skaro', 'Nicole', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (76, NULL, 'Knobbe', 'Trevor', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (77, NULL, 'Mattson', 'Lynn', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (81, NULL, 'Dolin', 'Tiana', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (82, NULL, 'Roth', 'Kim', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (83, NULL, 'Ellis', 'Senaida', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (85, NULL, 'Stepp', 'Rebecca', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (86, NULL, 'Starkey', 'Sheila', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (88, NULL, 'Correa', 'Jesse', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (89, NULL, 'Steinbroner', 'Cory', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (91, NULL, 'Loughran', 'Tom', 'East')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (92, NULL, 'Marin', 'Brandon', 'Support')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (93, NULL, 'Davis', 'Brandon', 'West')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (94, NULL, 'Gomez', 'Zandra', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (95, NULL, 'Gardner', 'Eddie', 'Central')
INSERT INTO [dbo].[Employees] (ID, Company, LastName, FirstName, City) VALUES (96, NULL, 'Hazelwood', 'Wendy', 'Central')

SET IDENTITY_INSERT [dbo].[Employees] OFF


/************************ ReformatsAQ2 table inserts ************************/
SET IDENTITY_INSERT [dbo].[ReformatsAQ2] ON

INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (1, '<No Reformat>')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (2, 'AAFS Advanced Financial')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (3, 'AAFS Asyst MERIT (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (4, 'AAFS Condo Manager (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (5, 'AAFS Jenark Vanguard')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (6, 'AAFS NoSplit QUICKBOOKS (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (7, 'AAFS Performance CAM (AltMemberID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (8, 'AAFS PROMAS Kallfelz (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (9, 'AAFS QUICKBOOKS (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (10, 'AAFS QUICKBOOKS (Alt MemberID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (11, 'AAFS Skyline (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (12, 'AAFS Thoroughbred')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (13, 'AAFS TOPS')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (14, 'AAFS TOPS (Alt AssocID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (15, 'AAFS TOPS (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (16, 'AAFS VMS Standard')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (17, 'AAFS VMS Standard (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (18, 'AAFS VMS Standard (AltMember ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (19, 'AAFS Voyager 2000 (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (20, 'AAFS Voyager APS')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (21, 'AAFS Voyager APS (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (22, 'PM Advantos')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (23, 'PM Advantos (Alt MemberID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (24, 'PM Asyst (Alt ID) MP AssocMgmt')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (25, 'PM Asyst (Alt MemberID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (26, 'PM C3 (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (27, 'PM CINC')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (28, 'PM JENARK (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (29, 'PM TOPS (Alt AssocID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (30, 'PM TOPS (Alt ID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (31, 'PM TOPS (Alt MemberID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (32, 'PM YARDI YEB (Alt AssocID)')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (33, 'PM YARDI YEB (Alt MemberID) Robin Oaks')
INSERT INTO [dbo].[ReformatsAQ2] (ID, ReformatName) VALUES (34, 'SQL QBOL')

SET IDENTITY_INSERT [dbo].[ReformatsAQ2] OFF


/************************ Software table inserts ************************/
SET IDENTITY_INSERT [dbo].[Software] ON

INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (2, 'ACCPAC')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (3, 'Advantos')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (4, 'AMS Pro')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (5, 'AMSI')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (6, 'AppFolio')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (7, 'Asyst')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (8, 'BJ Murray')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (9, 'Bo-Master')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (10, 'Buildium')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (11, 'C3')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (12, 'Caliber')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (13, 'Caliber - VMS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (14, 'CAM Accounting')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (15, 'Cam Cat (In-House)')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (16, 'Cinc')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (17, 'Cira Connect')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (18, 'Condo Manager')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (19, 'Custom')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (20, 'HA Software')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (21, 'In-House')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (22, 'JD Edwards')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (23, 'Jenark')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (24, 'JONAS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (25, 'Microsoft Dynamics')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (26, 'MTS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (27, 'N/A')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (28, 'Promas')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (29, 'Promise Software')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (30, 'Property Boulevard')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (31, 'QuickBooks')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (32, 'Quickbooks Online')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (33, 'QuickBooks Pro')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (34, 'Quicken')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (35, 'RealPage')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (36, 'Rent Manager')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (37, 'Sage')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (38, 'Sage Peachtree')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (39, 'Sage Timberline')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (40, 'Skyline')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (41, 'SPI Software')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (42, 'TimeShare Soft')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (43, 'TimeShareWare')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (44, 'TOPS 321')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (45, 'TOPS IQ')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (46, 'TOPS One')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (47, 'TOPS Pro')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (48, 'VMS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (49, 'VMS 1.7')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (50, 'VMS 2.0')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (51, 'Voyager')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (52, 'Yardi Genesis')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (53, 'Yardi Voyager')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (54, 'Alchemy')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (55, 'Appfolio - TOPs one')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (56, 'Asyst Data Group')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (57, 'Caliber (Reef Point)')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (58, 'CINC Systems')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (59, 'Condo Manager - Caliber')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (60, 'Converting from Yardi to VMS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (61, 'eUnify')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (62, 'MRI Software')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (63, 'MTS Software Solutions')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (64, 'Northstar')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (65, 'Other')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (66, 'Peachtree')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (67, 'Promise')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (68, 'Propertyware')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (69, 'Proprietary')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (70, 'QuickBooks - VMS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (71, 'QuickBooks/Eunify')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (72, 'Real Page')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (73, 'Sage/Peachtree')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (74, 'Timeshare Ware')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (75, 'TimeShareWare/SPI')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (76, 'TOPS')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (77, 'TOPS & Yardi')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (78, 'TOPS 4')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (79, 'TOPS 4.0')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (80, 'TOPS 4.1')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (81, 'TOPS Pro - TOPS One')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (82, 'TOPS Pro & Caliber')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (83, 'TOPS sdf')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (84, 'VMS (Own Version Purchased)')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (85, 'Voyager - Caliber')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (86, 'Yardi')
INSERT INTO [dbo].[Software] (ID, SoftwareName) VALUES (87, 'VMS 2018')

SET IDENTITY_INSERT [dbo].[Software] OFF